# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  esi: { enabled: true }
  fragments: { path: /_fragment }
  secret: "%env(APP_SECRET)%"
  #csrf_protection: true
  http_method_override: false
  handle_all_throwables: true
  router:
    default_uri: http://'%env(HOSTNAME)%'/docauposte

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    enabled: true
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
    gc_maxlifetime: 1800 # Session lifetime in seconds (e.g., 30 minutes)

  #esi: true
  #fragments: true
  php_errors:
    log: true

  # the IP address (or range) of your proxy
  trusted_proxies: "10.89.0.0/24, 172.21.0.254/16"
  # trust *all* "X-Forwarded-*" headers
  trusted_headers:
    [
      "x-forwarded-for",
      "x-forwarded-host",
      "x-forwarded-proto",
      "x-forwarded-port",
      "x-forwarded-prefix",
    ]

  # or, if your proxy instead uses the "Forwarded" header
when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
