# version: '3'

# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-15}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
version: '3.8'
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes :
    - ./database_data:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address : 172.20.0.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8082:80"
    networks:
      vpcbr:
        ipv4_address : 172.20.0.3
    depends_on:
      - database
  web:
    # image: bitnami/codeigniter:3.1.11
    # image: php:8.2-rc-apache
    # image: php-alpine:latest
    image: kiloutyg/po:docauposteweb
    # build: .
    # entrypoint: "./entrypoint.sh"
    restart: unless-stopped
    volumes:
  #    - ./myapp:/app/myapp
      - ./:/var/www
    ports:
      - "8000:80"
      - "9000:8000"
      - "9080:8080"
    depends_on :
      - database
    networks:
      vpcbr:
        ipv4_address : 172.20.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
