version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
    networks:
      vpcbr:
        ipv4_address : 172.20.0.5
###< symfony/mailer ###
