# Development Dockerfile

FROM node:14

# Install dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install

# Copy application code (if needed)
# In this case, we do NOT copy the application code
# COPY . .

# Expose port (if needed)
EXPOSE 3000

# Command to run your app
CMD ["npm", "start"] 