apiVersion: v1
kind: LimitRange
metadata:
  name: docauposte-database-pod-limits-range
  namespace: docauposte
spec:
  limits:
    - defaultRequest:
        memory: 8000Mi
        ephemeral-storage: 10000Mi
        cpu: 4
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-database-pod
  namespace: docauposte
  labels:
    app: docauposte-database
spec:
  securityContext:
    runAsNonRoot: true
  automountServiceAccountToken: false
  restartPolicy: Always
  initContainers:
    - name: copy-certificates-and-fix-permission-for-dap-db
      image: docker.io/library/busybox:stable
      command: ["/bin/sh", "-c"]
      args:
        - |
          cp /source/ca-cert.pem /dap-db-certs/;
          cp /source/server-cert.pem /dap-db-certs/;
          cp /source/server-key.pem /dap-db-certs/;
          chown mysql:mysql /dap-db-certs/*.pem;
          chmod 644 /dap-db-certs/ca-cert.pem /dap-db-certs/server-cert.pem;
          chmod 644 /dap-db-certs/server-key.pem;
      volumeMounts:
        - mountPath: /source/ca-cert.pem
          name: ca-cert
        - mountPath: /source/server-cert.pem
          name: server-cert
        - mountPath: /source/server-key.pem
          name: server-key
        - mountPath: /dap-db-certs
          name: dap-db-certs
  containers:
    - name: database
      image: docker.io/library/mariadb:lts-noble
      securityContext:
        allowPrivilegeEscalation: false
      env:
        - name: MARIADB_ROOT_PASSWORD_FILE
          value: run/secrets/root_password
        - name: MARIADB_DATABASE_FILE
          value: run/secrets/database_name
        - name: MARIADB_USER_FILE
          value: run/secrets/database_user
        - name: MARIADB_PASSWORD_FILE
          value: run/secrets/database_password
      volumeMounts:
        - mountPath: /run/secrets/root_password
          readOnly: true
          name: root_password
        - mountPath: /run/secrets/database_name
          readOnly: true
          name: database_name
        - mountPath: /run/secrets/database_user
          readOnly: true
          name: database_user
        - mountPath: /run/secrets/database_password
          readOnly: true
          name: database_password
        - mountPath: /var/lib/mysql
          name: database-data
        - mountPath: /etc/localtime
          name: localtime-settings
          readOnly: true
        - mountPath: /etc/mysql/my.cnf
          readOnly: true
          name: mysql-config
        - mountPath: /etc/mysql/ssl
          name: dap-db-certs
          readOnly: true
      resources:
        limits:
          memory: 8000Mi
          ephemeral-storage: 10000Mi
        requests:
          cpu: 4
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ${PWD}/secrets/root_password
        type: File
      name: root_password
    - hostPath:
        path: ${PWD}/secrets/database_name
        type: File
      name: database_name
    - hostPath:
        path: ${PWD}/secrets/database_user
        type: File
      name: database_user
    - hostPath:
        path: ${PWD}/secrets/database_password
        type: File
      name: database_password
    - hostPath:
        path: ${PWD}/database_data
        type: Directory
      name: database-data
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
    - hostPath:
        path: ${PWD}/secrets/ssl/ca-cert.pem
        type: File
      name: ca-cert
    - hostPath:
        path: ${PWD}/secrets/ssl/server-cert.pem
        type: File
      name: server-cert
    - hostPath:
        path: ${PWD}/secrets/ssl/server-key.pem
        type: File
      name: server-key
    - hostPath:
        path: ${PWD}/my.cnf
        type: File
      name: mysql-config
    - name: dap-db-certs
      emptyDir: {}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: docauposte-phpmyadmin-pod-limits-range
  namespace: docauposte
spec:
  limits:
    - defaultRequest:
        memory: 1000Mi
        ephemeral-storage: 500Mi
        cpu: 1
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-phpmyadmin-pod
  namespace: docauposte
  labels:
    app: docauposte-phpmyadmin
    traefik.enable: true
    traefik.http.routers.docauposte-phpmyadmin.rule: "Host(`${HOSTNAME}.ad.ponet`) && PathPrefix(`/dappma`) || Host(`${DOMAIN_NAME}.corp.ponet`) && PathPrefix(`/dappma`)"
    traefik.http.routers.docauposte-phpmyadmin.entrypoints: websecure
    traefik.http.routers.docauposte-phpmyadmin.tls: true
    traefik.http.routers.docauposte-phpmyadmin.middlewares: strip-docauposte-phpmyadmin-prefix
    traefik.http.services.docauposte-phpmyadmin.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-docauposte-phpmyadmin-prefix.stripPrefix.prefixes: /dappma
spec:
  securityContext:
    runAsNonRoot: true
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
    - name: phpmyadmin
      image: docker.io/phpmyadmin/phpmyadmin:5.2.2
      securityContext:
        allowPrivilegeEscalation: false
        # capabilities:
        #   drop:
        #     - ALL
      env:
        - name: PMA_HOST
          value: docauposte-database-pod
        - name: PMA_ABSOLUTE_URI
          value: https://${DOMAIN_NAME}.corp.ponet/dappma/
        - name: PMA_SSL
          value: "true"
        - name: PMA_SSL_CA
          value: /etc/phpmyadmin/ssl/ca-cert.pem
      volumeMounts:
        - mountPath: /etc/phpmyadmin/config.user.inc.php
          name: phpmyadmin-config
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime-settings
          readOnly: true
        - mountPath: /etc/phpmyadmin/ssl/ca-cert.pem
          name: ca-cert
          readOnly: true
      resources:
        limits:
          memory: 1000Mi
          ephemeral-storage: 500Mi
        requests:
          cpu: 1
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ${PWD}/config.user.inc.php
        type: File
      name: phpmyadmin-config
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
    - hostPath:
        path: ${PWD}/secrets/ssl/ca-cert.pem
        type: File
      name: ca-cert
---
apiVersion: v1
kind: LimitRange
metadata:
  name: docauposte-web-pod-limits-range
  namespace: docauposte
spec:
  limits:
    - defaultRequest:
        memory: 4000Mi
        ephemeral-storage: 15000Mi
        cpu: 4
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-web-pod
  namespace: docauposte
  labels:
    app: docauposte-web
    traefik.enable: true
    traefik.http.routers.docauposte-web.rule: "Host(`${HOSTNAME}.ad.ponet`) && PathPrefix(`/docauposte`) || Host(`${DOMAIN_NAME}.corp.ponet`) && PathPrefix(`/docauposte`)"
    traefik.http.routers.docauposte-web.entrypoints: websecure
    traefik.http.routers.docauposte-web.tls: true
    traefik.http.routers.docauposte-web.middlewares: strip-docauposte-web-prefix
    traefik.http.services.docauposte-web.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-docauposte-web-prefix.stripPrefix.prefixes: /docauposte
spec:
  securityContext:
    runAsNonRoot: true
  automountServiceAccountToken: false
  restartPolicy: Always
  initContainers:
    - name: copy-certificates-and-fix-permission-for-dap
      image: docker.io/library/busybox:stable
      command: ["/bin/sh", "-c"]
      args:
        - |
          cp /source/ca-cert.pem /dap-certs/;
          cp /source/server-cert.pem /dap-certs/;
          cp /source/server-key.pem /dap-certs/;
          cp /source/.env /dap-certs/;
          chmod 750 /var/www/public/doc;
          chown -R www-data:www-data /var/www/public/doc;
          chmod 640 /dap-certs/.env;
          chown www-data:www-data /dap-certs/.env;
          chmod 644 /dap-certs/ca-cert.pem /dap-certs/server-cert.pem;
          chmod 644 /dap-certs/server-key.pem;
          chown www-data:www-data /dap-certs/*.pem;
      volumeMounts:
        - mountPath: /source/ca-cert.pem
          name: ca-cert
        - mountPath: /source/server-cert.pem
          name: server-cert
        - mountPath: /source/server-key.pem
          name: server-key
        - mountPath: /dap-certs
          name: dap-certs
        - mountPath: /var/www/public/doc
          name: doc
        - mountPath: /var/www/.env
          name: dotenv
  containers:
    - name: web
      image: ghcr.io/${GITHUB_USER}/docauposte2:${APP_CONTEXT}-latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_NET_BIND_SERVICE
          drop:
            - ALL
      # command: ["./dev-entrypoint.sh"]
      env:
        - name: no_proxy
          value: .ponet
        - name: http_proxy
          value: ${PROXY_ENV}
        - name: APP_TIMEZONE
          value: ${APP_TIMEZONE}
        - name: https_proxy
          value: ${PROXY_ENV}
      volumeMounts:
        # - mountPath: /var/www
        #   name: web-data
        # - mountPath: /var/www/dev-entrypoint.sh
        #   name: dev-entrypoint
        - mountPath: /var/www/public/doc
          name: doc
        - mountPath: /etc/ssl/my-certs
          name: dap-certs
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime-settings
          readOnly: true
      resources:
        limits:
          memory: 4000Mi
          ephemeral-storage: 15000Mi
        requests:
          cpu: 4
  dnsPolicy: Default
  volumes:
    # - hostPath:
    #     path: ${PWD}/
    #     type: Directory
    #   name: web-data
    # - hostPath:
    #     path: ./dev-entrypoint.sh
    #     type: File
    #   name: dev-entrypoint
    - hostPath:
        path: ${PWD}/public/doc
        type: Directory
      name: doc
    - hostPath:
        path: ${PWD}/.env
        type: File
      name: dotenv
    - hostPath:
        path: ${PWD}/secrets/ssl/ca-cert.pem
        type: File
      name: ca-cert
    - hostPath:
        path: ${PWD}/secrets/ssl/server-cert.pem
        type: File
      name: server-cert
    - hostPath:
        path: ${PWD}/secrets/ssl/server-key.pem
        type: File
      name: server-key
    - hostPath:
        path: /etc/localtime
      name: localtime-settings
    - name: dap-certs
      emptyDir: {}
