apiVersion: v1
kind: Service
metadata:
  name: docauposte-database-service
spec:
  selector:
    app: docauposte-database
  ports:
    - port: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-database-pod
  labels:
    app: docauposte-database
spec:
  restartPolicy: Always
  containers:
    - name: database
      image: docker.io/library/mariadb:latest
      env:
        - name: MARIADB_ROOT_PASSWORD_FILE
          value: run/secrets/root_password
        - name: MARIADB_DATABASE_FILE
          value: run/secrets/database_name
        - name: MARIADB_USER_FILE
          value: run/secrets/database_user
        - name: MARIADB_PASSWORD_FILE
          value: run/secrets/database_password
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: secrets
          mountPath: /run/secrets
          readOnly: true
        - mountPath: /var/lib/mysql
          name: database-data
  dnsPolicy: Default
  volumes:
    - name: secrets
      hostPath:
        path: ./secrets
        type: Directory
    - hostPath:
        path: ./database_data
        type: DirectoryOrCreate
      name: database-data
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-phpmyadmin-pod
  labels:
    app: docauposte-phpmyadmin
    traefik.enable: true
    traefik.http.routers.docauposte-phpmyadmin.rule: PathPrefix(`/dappma`)
    traefik.http.routers.docauposte-phpmyadmin.entrypoints: web
    traefik.http.routers.docauposte-phpmyadmin.middlewares: strip-docauposte-phpmyadmin-prefix
    traefik.http.services.docauposte-phpmyadmin.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-docauposte-phpmyadmin-prefix.stripPrefix.prefixes: /dappma
spec:
  restartPolicy: Always
  containers:
    - name: phpmyadmin
      image: docker.io/phpmyadmin/phpmyadmin
      env:
        - name: PMA_HOST
          value: database
        - name: PMA_ABSOLUTE_URI
          value: http://${HOSTNAME}/dappma/
      volumeMounts:
        - mountPath: /etc/phpmyadmin/config.user.inc.php
          name: phpmyadmin-config
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./config.user.inc.php
        type: File
      name: phpmyadmin-config
---
apiVersion: v1
kind: Pod
metadata:
  name: docauposte-web-pod
  labels:
    app: docauposte-web
    traefik.enable: true
    traefik.http.routers.docauposte-web.rule: PathPrefix(`/docauposte`)
    traefik.http.routers.docauposte-web.entrypoints: web
    traefik.http.routers.docauposte-web.middlewares: strip-docauposte-web-prefix
    traefik.http.services.docauposte-web.loadbalancer.server.port: 80
    traefik.http.middlewares.strip-docauposte-web-prefix.stripPrefix.prefixes: /docauposte
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1129600513
  restartPolicy: Always
  containers:
    - name: web
      image: ghcr.io/${GITHUB_USER}/docauposte2:main
      command: ["./${APP_CONTEXT}-entrypoint.sh"]
      env:
        - name: no_proxy
          value: .ponet
        - name: http_proxy
          value: ${PROXY_ENV}
        - name: APP_TIMEZONE
          value: ${APP_TIMEZONE}
        - name: https_proxy
          value: ${PROXY_ENV}
      volumeMounts:
        - mountPath: /var/www
          name: web-data
  dnsPolicy: Default
  volumes:
    - hostPath:
        path: ./
        type: Directory
      name: web-data
